# -*- coding: utf-8 -*-
"""20615정현서_1.입력과 출력.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtW7q1gRTA09s4uN2kw9gTkanh9EeuwT

#1.출력하기 p1
"""

print(3+3)

print(3+4)
4*5
a = 1
b = 2
print(a+b)

a = '강아지'
b = '고양이'
print(a)
print(b)

print(" *       *")
print("  *     *")
print("   *   *")
print("    * *")
print("     *")

a = '강아지'
b = '고양이'
print(a, end = '')
print(b)

print(34, end = '^^')
print(78)

a = 12
b = 34
print(a,b)

"""#1. 출력하기 p2"""

a=12
b=34
print(a, b, sep =',')

s = '서울'
d = '대전'
g = '대구'
b = '부산'
print(s, d, g, b, sep ='찍고 ', end="찍고")

print(12, 34, 56, sep='^^', end = '-->')
print(78)

a = 13
b = 21
print(a, b)
print(a + b)
print(a, b, sep='')
print(a, b, end='')

"""#2. 입력하기 p2"""

age = input('몇 살이세요?')
print(age)

name = input('이름을 입력하세요: ')
print("안녕하세요", name, "님!")

f1 = input('첫 번째 과일 입력: ')
f2 = input('두 번째 과일 입력: ')
print(f1, "와(과)", f2, "은(는) 내가 좋아하는 과일이다.")

year = input('몇 년도? ')
month = input("몇 월? ")
day = input("몇 일? ")
print(year, month, day, sep = " . ")

age = input('몇 살이세요?')
print(age + age)

"""# 2. 입력하기 p3"""

age = input('몇 살이세요?')
age = int(age)
print(age+age)

price = int(input('가격을 입력하세요 : '))
num = int(input('개수를 입력하세요: '))
sum= price * num
print('총액은', sum, "원입니다")

width = int(input('사각형의 가로: '))
height = int(input('사각형의 세로: '))
print("사각형의 면적은", width*height, "입니다.")

name = input('이름? ')
year = int(input('태어난 해는? '))
print(name, '님의 나이는', (2023-year+1),'세 입니다.')

price = int(input('물건의 가격? '))
num = int(input('물건 구매 개수? '))
money = int(input('지불한 돈? '))
print('거스름돈은', money-price*num, '원입니다.')

"""#1. 변수 p4"""

score = 100
print(score)
print(type(score))

score = 'high'
print(score)
print(type(score))

"""#1. 변수 p5"""

num = 123456789
print(num)
print(type(num))

num = -20909
print(num)
print(type(num))

a= 1.5
b = -3.5
print(a, b)
print(type(a), type(b))

x=3.3764
y = 6/2
print(x, y)
print(type(x), type(y))

a = "Korea 서울 1234"
print(a)
print(type(a))

a = 30
print(a)
print(type(a))

b = '30'
print(b)
print(type(b))

a = 5
b = a==5
print(b)

if a ==5:
  print("a는 5")

"""#1. 변수 p6"""

a = input('첫 번째 숫자를 입력하세요: ')
b = input('두 번째 숫자를 입력하세요: ')
c = a + b
print(c)

a = input('첫 번째 숫자를 입력하세요: ')
b = input('두 번째 숫자를 입력하세요: ')
c = int(a) + int(b)
print(c)

inch = input('인치를 입력하세요 : ')
cm = float(inch)*2.54
print('센티미터:', cm,"cm")

num = input('반지름은? ')
num2 = float(num)*2*3.14
num3 = float(num)*float(num)*3.14

print('반지름이', num,'인 원의 둘레는', round(num2, 2),'이고, 면적은 ', num3.,'이다.')

high = input('현재 키는? ')
lehigh = input('5개월 후의 목표 키는? ')
mo = (float(lehigh)-float(high))/5
print('한달에', round(mo, 2),"cm씩 성장해 보세요!")

book = input('책 값: ')
discount = input('할인율(%): ')
delivery = input('배송비: ')
total = (float(book)+float(delivery))-float(book)/100*float(discount)
print('결제하실 금액은 ', round(total, 2), '원 입니다.')

num1 = int(input('첫 번째 과목: '))
num2 = int(input('두 번째 과목: '))
sum = num1 + num2
avg = float(sum)/2
print("합계:", sum, "평균:", round(avg, 2))

mic = input('삼각형의 밑변 길이 : ')
high = input('삼각형의 높이 : ')
num = float(mic) * float(high)/2
print('삼각형의 면적 : ', round(num, 2))

kg = float(input('킬로그램(kg) 입력: '))
pound = kg*2.2046
print(kg,'kg은', round(pound, 4), '파운드입니다.')

"""# 연산자 p7"""

print(5+2)
print(5-2)
print(5*2)
print(5/2)
print(5**2)
print(5//2)
print(5%2)

x = 10 % 3
print(x)
y = 7//3
print(y)

a = 10
b = 20
c = a + b * 10 - 5 / 5
print(c)

x = 2**3
print(x)

y = 10**4
print(y)

hello = '안녕 ' * 5
print(hello)

s1 = "대한민국"
s2 = "만세"
print(s1+s2)
print(s1*5)

print("korea"+str(2021))
print(110+int(22))
print(10 + int(22.5))
print(10 + int(float(22.5)))
print("korea"+2021)

x = 10
x += 20
print(x)

a = 5
a = a+1
print(a)

a=5
a +=1
print(a)

a -= 5
print(a)

a*=2
print(a)

x = 3
y = 5
x *= x+y
print(x)

"""##연산자복습"""

money = int(input('투입한 돈: '))
price = int(input('물건 값: '))
change = money-price
five = change // 500
one = (change-five*500) // 100
print('거스름돈', change)
print('500원 동전의 개수:', five)
print('100원 동전의 개수', one);